### ISSUE TITLE
As a user of the counties_demo notebook I must have a .bdb file that meets the below requirements, so that I can show query results on a map and tell a compelling story

### ISSUE THREAD

**Issue by tctrautman** [probcomp/counties-demo#1]
- [ ] Upon creation, the .bdb file was built with at least 8 models
- [ ] Upon creation, the  .bdb file was built with at least ~100 iterations of `ANALYZE`
- [ ] Upon creation, the .bdb file overrode the `state_counties_fips` column as a `CHAR` (rather than a number)
- [ ] Upon creation, the .bdb file should write the `Population` column as a stattype of `NOMINAL`

**Comment by tctrautman** [comment]
This has happened, and now the lab will be building .bdb files going forward.
