### ISSUE TITLE
As a user of the counties_demo notebook, the demo must live in a repo with the requirements laid out in the roadmap document, so that the repo can be run with a reasonable level of certainty that the results will line up with the narrative, and that the data preparation steps can be easily replicated

### ISSUE THREAD

**Issue by tctrautman** [probcomp/counties-demo#4]
The section of the roadmap document is here: https://docs.google.com/document/d/1cl6wLr2OsLHCDTY9HNR5-IJjPkvicUVWDt0MT6NurgQ/edit#heading=h.dgd4guiav5i

Requirements laid out in the document are:
- [ ] The repo must have a text file that lists the "raw" / "dirty" source .csv files that were used as inputs for creating a clean .csv file
- [ ] The repo must have a text file that serves as instructions for how to clean the raw .csv files and join them together
- [ ] The repo must have a script that produces a .bdb file from the cleaned .csv
- [ ] The repo must have a text file named `DEMO_BDB_URL.txt`, which contains a URL for a .bdb file in dropbox
- [ ] The repo must have a script named `counties_demo_test.py`, which tests the .bdb file (either on a user's local machine or pulled down onto the server from the URL) is correct enough to be consistent with the narrative, though it does not have to be exactly right.
- [ ] The repo must have a Jupyter notebook that a user can walk through with an audience
